# -*- coding: utf-8 -*-
"""YOLOV11_FINAL (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cnFpQfEix8lsz73Sb3D_my17h0PNm2kZ

# YOLOv11 Thesis Notebook
**Three pipelines:** Raw | Zero-DCE | Zero-3DCE

Run all cells top to bottom. Never skip a cell within a section.
"""

# ── Install dependencies ─────────────────────────────────────────
!pip install roboflow ultralytics pytorch-msssim -q
print('Dependencies installed ✓')

# ── Download dataset and create 3 isolated copies ────────────────
from roboflow import Roboflow
import shutil, os

rf      = Roboflow(api_key="s3tKV1FBAKtkaJ4hAwYw")
project = rf.workspace("thesis-fwlrq").project("annotations-okdeo")
dataset = project.version(1).download("yolov11")
src     = dataset.location
print(f'Downloaded to: {src}')

for dest in [
    '/content/datasets/Raw_Dataset',
    '/content/datasets/ZeroDCE_Dataset',
    '/content/datasets/Zero3DCE_Dataset',
]:
    if os.path.exists(dest):
        shutil.rmtree(dest)
    shutil.copytree(src, dest)
    print(f'Created: {dest}')

print('\n✅ All datasets ready.')

"""## Pipeline 1: No Enhancement (Raw) + YOLOv11"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!yolo task=detect mode=train \
    model=yolo11s.pt \
    data=/content/datasets/Raw_Dataset/data.yaml \
    epochs=100 \
    imgsz=640 \
    plots=True \
    project=/content/runs/thesis \
    name=raw_experiment

"""## Pipeline 2: Zero-DCE Enhancement + YOLOv11"""

import os

# Clone Zero-DCE repo if needed
if not os.path.exists('/content/Zero-DCE/Zero-DCE_code/model.py'):
    !git clone https://github.com/Li-Chongyi/Zero-DCE.git /content/Zero-DCE
print('Zero-DCE repo ready ✓')

import importlib.util, sys, os

for key in list(sys.modules.keys()):
    if key in ('model', 'dataloader', 'Myloss'):
        del sys.modules[key]

BASE = '/content/Zero-DCE/Zero-DCE_code'

def load_module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod  = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod

model_mod = load_module('model', f'{BASE}/model.py')
from model import enhance_net_nopool
print('Zero-DCE model loaded from:', model_mod.__file__)

import torch, glob
from torchvision import transforms
from PIL import Image
from model import enhance_net_nopool

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Load pretrained Zero-DCE weights
ZERODCE_WEIGHTS = '/content/Zero-DCE/Zero-DCE_code/snapshots/Epoch99.pth'
if not os.path.exists(ZERODCE_WEIGHTS):
    # Use the weights bundled with the repo if available
    snaps = glob.glob('/content/Zero-DCE/Zero-DCE_code/snapshots/*.pth')
    if snaps:
        ZERODCE_WEIGHTS = sorted(snaps)[-1]
    else:
        raise FileNotFoundError('No Zero-DCE weights found. Check /content/Zero-DCE/Zero-DCE_code/snapshots/')

zerodce_net = enhance_net_nopool().to(device)
zerodce_net.load_state_dict(torch.load(ZERODCE_WEIGHTS, map_location=device))
zerodce_net.eval()
print(f'Zero-DCE weights loaded from: {ZERODCE_WEIGHTS}')

def enhance_zerodce(img_path):
    img            = Image.open(img_path).convert('RGB')
    orig_w, orig_h = img.size
    tf             = transforms.Compose([transforms.Resize((512,512)), transforms.ToTensor()])
    t              = tf(img).unsqueeze(0).to(device)
    with torch.no_grad():
        result   = zerodce_net(t)
        enhanced = result[-2]  # second to last is the enhanced image
    out = enhanced.squeeze(0).cpu().clamp(0, 1)
    return transforms.ToPILImage()(out).resize((orig_w, orig_h), Image.LANCZOS)

# Enhance all splits
for split in ['train', 'valid', 'test']:
    img_dir = f'/content/datasets/ZeroDCE_Dataset/{split}/images'
    if not os.path.exists(img_dir):
        print(f'  Skipping {split} — not found')
        continue
    imgs = glob.glob(f'{img_dir}/*.jpg') + glob.glob(f'{img_dir}/*.png')
    print(f'Enhancing {len(imgs)} {split} images with Zero-DCE...')
    for idx, fpath in enumerate(imgs):
        enhance_zerodce(fpath).save(fpath)
        if (idx+1) % 50 == 0 or (idx+1) == len(imgs):
            print(f'  {idx+1}/{len(imgs)}')
    print(f'  {split} done ✓')

print('\n✅ Zero-DCE enhancement complete.')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!yolo task=detect mode=train \
    model=yolo11s.pt \
    data=/content/datasets/ZeroDCE_Dataset/data.yaml \
    epochs=100 \
    imgsz=640 \
    plots=True \
    project=/content/runs/thesis \
    name=zerodce_experiment

"""## Pipeline 3: Zero-3DCE Enhancement + YOLOv11

> **Prerequisite:** Run `Zero3DCE_Train.ipynb` first to produce `zero3dce_final.pth` in your Google Drive.
"""

# ── Mount Drive and set checkpoint path ──────────────────────────
from google.colab import drive
drive.mount('/content/drive')

import os
SAVE_DIR   = '/content/drive/MyDrive/zero3dce/checkpoints'
final_path = os.path.join(SAVE_DIR, 'zero3dce_final.pth')

if not os.path.exists(final_path):
    raise FileNotFoundError(
        f'Checkpoint not found at {final_path}.\n'
        'Run Zero3DCE_Train.ipynb first to train and save the model.'
    )
print(f'Checkpoint found: {final_path} ✓')

# ── Zero-3DCE Architecture (must match Zero3DCE_Train.ipynb) ─────
import torch
import torch.nn as nn
import torch.nn.functional as F

class SepConv3d(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size=3, padding=1):
        super().__init__()
        self.depthwise = nn.Conv3d(in_channels, in_channels, kernel_size=kernel_size,
                                   padding=padding, groups=in_channels, bias=False)
        self.pointwise = nn.Conv3d(in_channels, out_channels, kernel_size=1, bias=False)
        self.bn  = nn.BatchNorm3d(out_channels)
        self.act = nn.ReLU(inplace=True)
    def forward(self, x):
        return self.act(self.bn(self.pointwise(self.depthwise(x))))

class SpatialAttention(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv    = nn.Conv3d(2, 1, kernel_size=7, padding=3, bias=False)
        self.sigmoid = nn.Sigmoid()
    def forward(self, x):
        avg   = torch.mean(x, dim=1, keepdim=True)
        mx, _ = torch.max(x, dim=1, keepdim=True)
        return x * self.sigmoid(self.conv(torch.cat([avg, mx], dim=1)))

class EncoderBlock(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.conv = SepConv3d(in_ch, out_ch)
        self.attn = SpatialAttention()
        self.pool = nn.MaxPool3d(kernel_size=(1,2,2), stride=(1,2,2))
    def forward(self, x):
        x = self.attn(self.conv(x))
        return self.pool(x), x

class Zero3DCE(nn.Module):
    def __init__(self, num_iterations=8):
        super().__init__()
        self.num_iterations = num_iterations
        self.enc1       = EncoderBlock(3,  32)
        self.enc2       = EncoderBlock(32, 32)
        self.enc3       = EncoderBlock(32, 32)
        self.bottleneck = SepConv3d(32, 32)
        self.dec1       = SepConv3d(64, 32)
        self.dec2       = SepConv3d(64, 32)
        self.dec3       = SepConv3d(64, 24)
        self.up         = nn.Upsample(scale_factor=(1,2,2), mode='trilinear', align_corners=False)
        self.tanh       = nn.Tanh()
    def apply_curve(self, frame, alpha):
        return torch.clamp(frame + alpha * frame * (frame - 1), 0, 1)
    def forward_with_alphas(self, x):
        x1, skip1 = self.enc1(x)
        x2, skip2 = self.enc2(x1)
        x3, skip3 = self.enc3(x2)
        xb = self.bottleneck(x3)
        xb = self.dec1(torch.cat([self.up(xb), skip3], dim=1))
        xb = self.dec2(torch.cat([self.up(xb), skip2], dim=1))
        xb = self.dec3(torch.cat([self.up(xb), skip1], dim=1))
        alpha_maps = self.tanh(xb)
        enhanced   = x
        for i in range(self.num_iterations):
            g = (i % 3) * 8
            enhanced = self.apply_curve(enhanced, alpha_maps[:, g:g+3])
        return enhanced, alpha_maps

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Architecture defined ✓  Device: {device}')

# ── Load checkpoint and enhance Zero3DCE_Dataset ─────────────────
import glob
from torchvision import transforms
from PIL import Image

model_inf = Zero3DCE().to(device)
state     = torch.load(final_path, map_location=device)
model_inf.load_state_dict(
    state['model'] if isinstance(state, dict) and 'model' in state else state
)
model_inf.eval()
print(f'Loaded: {final_path}')

def enhance_zero3dce(img_path, blend=0.65):
    img            = Image.open(img_path).convert('RGB')
    orig_w, orig_h = img.size
    tf             = transforms.Compose([transforms.Resize((256,256)), transforms.ToTensor()])
    t              = tf(img).unsqueeze(0)
    clip           = torch.stack([t, t], dim=2).to(device)
    with torch.no_grad():
        enhanced, _ = model_inf.forward_with_alphas(clip)
    out          = enhanced[0, :, 0].cpu().clamp(0, 1)
    enhanced_img = transforms.ToPILImage()(out).resize((orig_w, orig_h), Image.LANCZOS)
    # Blend: 65% enhanced + 35% original — reduces overexposure on bright CCTV zones
    return Image.blend(img.resize((orig_w, orig_h)), enhanced_img, alpha=blend)

for split in ['train', 'valid', 'test']:
    img_dir = f'/content/datasets/Zero3DCE_Dataset/{split}/images'
    if not os.path.exists(img_dir):
        print(f'  Skipping {split} — not found')
        continue
    imgs = glob.glob(f'{img_dir}/*.jpg') + glob.glob(f'{img_dir}/*.png')
    print(f'Enhancing {len(imgs)} {split} images...')
    for idx, fpath in enumerate(imgs):
        enhance_zero3dce(fpath).save(fpath)
        if (idx+1) % 50 == 0 or (idx+1) == len(imgs):
            print(f'  {idx+1}/{len(imgs)}')
    print(f'  {split} done ✓')

print('\n✅ Zero-3DCE enhancement complete. Ready for YOLO training.')

from roboflow import Roboflow
import shutil, os

rf      = Roboflow(api_key="s3tKV1FBAKtkaJ4hAwYw")
project = rf.workspace("thesis-fwlrq").project("annotations-okdeo")
dataset = project.version(1).download("yolov11")

src  = dataset.location
dest = '/content/datasets/Zero3DCE_Dataset'
if os.path.exists(dest):
    shutil.rmtree(dest)
shutil.copytree(src, dest)
print('Zero3DCE_Dataset reset to raw images ✓')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!yolo task=detect mode=train \
    model=yolo11s.pt \
    data=/content/datasets/Zero3DCE_Dataset/data.yaml \
    epochs=100 \
    imgsz=640 \
    plots=True \
    project=/content/runs/thesis \
    name=zero3dce_experiment

from google.colab import drive
drive.mount('/content/drive')

import shutil, os

DEST = '/content/drive/MyDrive/thesis_exports'
os.makedirs(DEST, exist_ok=True)

print('Zipping and saving to Drive...')

shutil.make_archive(f'{DEST}/Raw_Dataset',      'zip', '/content/datasets/Raw_Dataset')
print('Raw_Dataset.zip ✓')

shutil.make_archive(f'{DEST}/ZeroDCE_Dataset',  'zip', '/content/datasets/ZeroDCE_Dataset')
print('ZeroDCE_Dataset.zip ✓')

shutil.make_archive(f'{DEST}/Zero3DCE_Dataset', 'zip', '/content/datasets/Zero3DCE_Dataset')
print('Zero3DCE_Dataset.zip ✓')

shutil.make_archive(f'{DEST}/raw_results',      'zip', '/content/runs/thesis/raw_experiment')
print('raw_results.zip ✓')

shutil.make_archive(f'{DEST}/zerodce_results',  'zip', '/content/runs/thesis/zerodce_experiment')
print('zerodce_results.zip ✓')

shutil.make_archive(f'{DEST}/zero3dce_results', 'zip', '/content/runs/thesis/zero3dce_experiment')
print('zero3dce_results.zip ✓')

shutil.copy('/content/runs/thesis/raw_experiment/weights/best.pt',      f'{DEST}/raw_best.pt')
shutil.copy('/content/runs/thesis/zerodce_experiment/weights/best.pt',  f'{DEST}/zerodce_best.pt')
shutil.copy('/content/runs/thesis/zero3dce_experiment/weights/best.pt', f'{DEST}/zero3dce_best.pt')
print('All weights ✓')

print(f'\n✅ Everything saved to Google Drive at: {DEST}')
print('Download from drive.google.com → thesis_exports folder')