# -*- coding: utf-8 -*-
"""Zero3DCE_Train (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b8b30nLIET5Balgi3XFB4VbyzfP4lEhD

# Zero-3DCE Training from Scratch
**Based on:** Tatana et al. (2025)

Run all cells top to bottom. Never skip a cell.

## Step 1: Mount Drive and Download Training Datasets
"""

from google.colab import drive
drive.mount('/content/drive')

import os, zipfile, shutil, glob
!pip install gdown -q
import gdown

# ── PATHS ─────────────────────────────────────────────────────────────
DRIVE_ROOT = '/content/drive/MyDrive/zero3dce'
DATA_DIR   = os.path.join(DRIVE_ROOT, 'dataset')
SAVE_DIR   = os.path.join(DRIVE_ROOT, 'checkpoints')
RESUME     = None  # set to e.g. SAVE_DIR+'/zero3dce_epoch010.pth' to resume
# ─────────────────────────────────────────────────────────────────────

for d in [DATA_DIR, SAVE_DIR]:
    os.makedirs(d, exist_ok=True)

def count_images(folder):
    if not os.path.exists(folder): return 0
    exts = ('.jpg','.jpeg','.png','.bmp')
    return sum(1 for r,_,fs in os.walk(folder) for f in fs if f.lower().endswith(exts))


# ══════════════════════════════════════════════════════════════════════
# Paper datasets (Tatana et al. 2025): DICM, LIME, LOL, SICEMix,
# LLVIP, BVI-RLV, Dark48  — sourced from LLIE_Survey repo
# ══════════════════════════════════════════════════════════════════════

# ── 1. DICM (via gdown folder) ────────────────────────────────────────
dicm_dir = os.path.join(DATA_DIR, 'DICM')
if count_images(dicm_dir) < 5:
    print('Downloading DICM...')
    os.makedirs(dicm_dir, exist_ok=True)
    gdown.download_folder(id='1wyS2HyzcNnWMwoJNMPf4hCTMtCy_6Pec',
                          output=dicm_dir, quiet=False, use_cookies=False, remaining_ok=True)
    print(f'  DICM: {count_images(dicm_dir)} images')
else:
    print(f'DICM already present: {count_images(dicm_dir)} images')


# ── 2. NPE / MEF (via gdown folder) ───────────────────────────────────
npe_ids = {
    'NPE-ex1': '1pgqsVT3avCIPUooYBzOMPF6rhQhakhPN',
    'NPE-ex2': '1kSIqCbhs07mZQt6U9wo7RLZ42giAedL3',
    'NPE-ex3': '1Yc0y7LpGEIfWAnl9ZUJWZkeR90dM6cNE',
    'MEF':     '1Vl-Iub172ivdkEFT1zr2IbnBGpQnbwkk',
}
for name, fid in npe_ids.items():
    out = os.path.join(DATA_DIR, name)
    if count_images(out) < 5:
        print(f'Downloading {name}...')
        os.makedirs(out, exist_ok=True)
        gdown.download_folder(id=fid, output=out, quiet=False,
                              use_cookies=False, remaining_ok=True)
        print(f'  {name}: {count_images(out)} images')
    else:
        print(f'{name} already present: {count_images(out)} images')


# ── 3. LOL dataset (manual upload required) ───────────────────────────
lol_dir = os.path.join(DATA_DIR, 'LOL')
lol_zip = os.path.join(DRIVE_ROOT, 'lol.zip')
if count_images(lol_dir) < 10:
    if os.path.exists(lol_zip):
        print('Extracting LOL...')
        os.makedirs(lol_dir, exist_ok=True)
        with zipfile.ZipFile(lol_zip) as z:
            z.extractall(lol_dir)
        print(f'  LOL: {count_images(lol_dir)} images')
    else:
        print('[OPTIONAL] LOL dataset not found — skipping.')
        print('  To add: download from https://daooshee.github.io/BMVC2018website/')
        print(f'  Upload zip to Drive at: {lol_zip}  then re-run.')
else:
    print(f'LOL already present: {count_images(lol_dir)} images')


# ── 4. LIME dataset (via gdown) ───────────────────────────────────────
lime_dir = os.path.join(DATA_DIR, 'LIME')
if count_images(lime_dir) < 5:
    print('Downloading LIME...')
    os.makedirs(lime_dir, exist_ok=True)
    gdown.download_folder(id='1OLmSGOSEM3FDTyaroUqZbqRvSGI5NBHW',
                          output=lime_dir, quiet=False, use_cookies=False, remaining_ok=True)
    print(f'  LIME: {count_images(lime_dir)} images')
else:
    print(f'LIME already present: {count_images(lime_dir)} images')


# ── 5. VV dataset (extra low-light, from LLIE survey) ─────────────────
vv_dir = os.path.join(DATA_DIR, 'VV')
if count_images(vv_dir) < 5:
    print('Downloading VV...')
    os.makedirs(vv_dir, exist_ok=True)
    gdown.download_folder(id='1Bh0NrPJDOoNYQVJVaSPRoiJzN-R9BPWP',
                          output=vv_dir, quiet=False, use_cookies=False, remaining_ok=True)
    print(f'  VV: {count_images(vv_dir)} images')
else:
    print(f'VV already present: {count_images(vv_dir)} images')


# ── 6. Copy your Roboflow CCTV frames into training data ──────────────
# Critical: teaches model your specific surveillance lighting conditions
surv_train = os.path.join(DATA_DIR, 'surveillance_cctv')
os.makedirs(surv_train, exist_ok=True)
roboflow_splits = [
    '/content/datasets/Raw_Dataset/train/images',
    '/content/datasets/Raw_Dataset/valid/images',
    '/content/datasets/Raw_Dataset/test/images',
]
surv_copied = 0
for split_dir in roboflow_splits:
    if not os.path.exists(split_dir):
        continue
    for f in (glob.glob(f'{split_dir}/*.jpg') + glob.glob(f'{split_dir}/*.png')):
        dst = os.path.join(surv_train, os.path.basename(f))
        if not os.path.exists(dst):
            shutil.copy(f, dst)
            surv_copied += 1
if surv_copied > 0:
    print(f'Copied {surv_copied} CCTV surveillance frames into training data ✓')
elif count_images(surv_train) > 0:
    print(f'Surveillance frames already present: {count_images(surv_train)} images')
else:
    print('[NOTE] No Roboflow dataset found at /content/datasets/Raw_Dataset.')
    print('  Run the dataset download cell in YOLOV11_FINAL.ipynb first, then re-run this cell.')


# ── Summary ───────────────────────────────────────────────────────────
total = count_images(DATA_DIR)
print(f'\n=== Dataset Summary ===')
for sub in sorted(os.listdir(DATA_DIR)):
    n = count_images(os.path.join(DATA_DIR, sub))
    if n > 0:
        print(f'  {sub:<25}: {n} images')
print(f'  {"TOTAL":<25}: {total} images')
print(f'\nCheckpoints will save to: {SAVE_DIR}')
print('Ready — proceed to Step 2.')

"""## Step 2: Install Dependencies"""

!pip install pytorch-msssim -q
print('Dependencies installed ✓')

"""## Step 3: Model Architecture
Implements Zero-3DCE from Section 3.1.1 of Tatana et al. (2025).

- `SepConv3d`: 3D Separable Convolution (Eq. 1-5)
- `SpatialAttention`: guides network to under-exposed regions (Section 3.1.2)
- `Zero3DCE`: full encoder-decoder, 24 curve maps, applies Eq. 6 iteratively 8 times

"""

import torch
import torch.nn as nn
import torch.nn.functional as F


class SepConv3d(nn.Module):
    """Depthwise + Pointwise 3D conv (Eq. 1-5). ~6.83% ops of standard 3D conv."""
    def __init__(self, in_channels, out_channels, kernel_size=3, padding=1):
        super().__init__()
        self.depthwise = nn.Conv3d(
            in_channels, in_channels,
            kernel_size=kernel_size, padding=padding,
            groups=in_channels, bias=False
        )
        self.pointwise = nn.Conv3d(in_channels, out_channels, kernel_size=1, bias=False)
        self.bn  = nn.BatchNorm3d(out_channels)
        self.act = nn.ReLU(inplace=True)

    def forward(self, x):
        return self.act(self.bn(self.pointwise(self.depthwise(x))))


class SpatialAttention(nn.Module):
    """Avg+Max pool -> concat -> 7x7x7 conv -> sigmoid -> reweight (Section 3.1.2)."""
    def __init__(self):
        super().__init__()
        self.conv    = nn.Conv3d(2, 1, kernel_size=7, padding=3, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg    = torch.mean(x, dim=1, keepdim=True)
        mx, _  = torch.max(x, dim=1, keepdim=True)
        attn   = self.sigmoid(self.conv(torch.cat([avg, mx], dim=1)))
        return x * attn


class EncoderBlock(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.conv = SepConv3d(in_ch, out_ch)
        self.attn = SpatialAttention()
        self.pool = nn.MaxPool3d(kernel_size=(1,2,2), stride=(1,2,2))

    def forward(self, x):
        x    = self.attn(self.conv(x))
        skip = x
        return self.pool(x), skip


class Zero3DCE(nn.Module):
    """
    Input:  [B, 3, D=2, H, W]  low-light video clip
    Output: [B, 3, D=2, H, W]  enhanced clip
    """
    def __init__(self, num_iterations=8):
        super().__init__()
        self.num_iterations = num_iterations
        self.enc1       = EncoderBlock(3,  32)
        self.enc2       = EncoderBlock(32, 32)
        self.enc3       = EncoderBlock(32, 32)
        self.bottleneck = SepConv3d(32, 32)
        self.dec1       = SepConv3d(64, 32)
        self.dec2       = SepConv3d(64, 32)
        self.dec3       = SepConv3d(64, 24)
        self.up         = nn.Upsample(scale_factor=(1,2,2), mode='trilinear', align_corners=False)
        self.tanh       = nn.Tanh()

    def apply_curve(self, frame, alpha):
        """Equation 6: I = i + alpha * i * (i - 1)"""
        return torch.clamp(frame + alpha * frame * (frame - 1), 0, 1)

    def forward(self, x):
        enhanced, _ = self.forward_with_alphas(x)
        return enhanced

    def forward_with_alphas(self, x):
        x1, skip1 = self.enc1(x)
        x2, skip2 = self.enc2(x1)
        x3, skip3 = self.enc3(x2)
        xb        = self.bottleneck(x3)
        xb        = self.dec1(torch.cat([self.up(xb), skip3], dim=1))
        xb        = self.dec2(torch.cat([self.up(xb), skip2], dim=1))
        xb        = self.dec3(torch.cat([self.up(xb), skip1], dim=1))
        alpha_maps = self.tanh(xb)
        enhanced   = x
        for i in range(self.num_iterations):
            g        = (i % 3) * 8
            enhanced = self.apply_curve(enhanced, alpha_maps[:, g:g+3])
        return enhanced, alpha_maps


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {device}')
model = Zero3DCE().to(device)
print(f'Parameters: {sum(p.numel() for p in model.parameters()):,}')
dummy = torch.rand(2, 3, 2, 256, 256).to(device)
with torch.no_grad():
    out, alphas = model.forward_with_alphas(dummy)
print(f'Input  shape: {dummy.shape}')
print(f'Output shape: {out.shape}  range [{out.min():.3f}, {out.max():.3f}]')
print('Architecture OK ✓')

"""## Step 4: Loss Functions
All 6 losses from Section 3.1.3, Eq. 7-14.

"""

from pytorch_msssim import ms_ssim


class ColorConstancyLoss(nn.Module):
    """Eq. 7-8"""
    def forward(self, enhanced):
        mean   = enhanced.mean(dim=[-2,-1])
        R, G, B = mean[:,0], mean[:,1], mean[:,2]
        return torch.mean(torch.sqrt((R-G)**2 + (R-B)**2 + (G-B)**2 + 1e-6))


class SpatialConsistencyLoss(nn.Module):
    """Eq. 9"""
    def __init__(self):
        super().__init__()
        kernels = [
            [[0,0,0],[-1,1,0],[0,0,0]],
            [[0,0,0],[0,1,-1],[0,0,0]],
            [[0,-1,0],[0,1,0],[0,0,0]],
            [[0,0,0],[0,1,0],[0,-1,0]],
        ]
        self.register_buffer('weights', torch.FloatTensor(kernels).unsqueeze(1))

    def _gray(self, t):
        B,C,D,H,W = t.shape
        return (0.299*t[:,0] + 0.587*t[:,1] + 0.114*t[:,2]).reshape(B*D,1,H,W)

    def forward(self, enhanced, original):
        eg, og = self._gray(enhanced), self._gray(original)
        loss = 0
        for w in self.weights:
            w     = w.unsqueeze(0)
            loss += torch.mean((F.conv2d(eg,w,padding=1).abs() - F.conv2d(og,w,padding=1).abs())**2)
        return loss / 4.0


class ExposureControlLoss(nn.Module):
    """Eq. 10"""
    def __init__(self, patch_size=16, E=0.4):
        super().__init__()
        self.E    = E
        self.pool = nn.AvgPool2d(patch_size)

    def forward(self, enhanced):
        B,C,D,H,W = enhanced.shape
        gray = (0.299*enhanced[:,0] + 0.587*enhanced[:,1] + 0.114*enhanced[:,2]).reshape(B*D,1,H,W)
        return torch.mean((self.pool(gray) - self.E)**2)


class IlluminationSmoothnessLoss(nn.Module):
    """Eq. 11"""
    def forward(self, alpha_maps):
        B,C,D,H,W = alpha_maps.shape
        eps   = 1e-6
        d_tv  = ((alpha_maps[:,:,1:]    - alpha_maps[:,:,:-1])**2).sum()
        h_tv  = ((alpha_maps[:,:,:,1:]  - alpha_maps[:,:,:,:-1])**2).sum()
        w_tv  = ((alpha_maps[:,:,:,:,1:]- alpha_maps[:,:,:,:,:-1])**2).sum()
        return (2/B) * (
            d_tv / (C*(D-1)*H*W + eps) +
            h_tv / (C*D*(H-1)*W + eps) +
            w_tv / (C*D*H*(W-1) + eps)
        )


class EdgeDetectionLoss(nn.Module):
    """Eq. 12"""
    def __init__(self):
        super().__init__()
        sx = torch.FloatTensor([[-1,0,1],[-2,0,2],[-1,0,1]]).unsqueeze(0).unsqueeze(0)
        sy = torch.FloatTensor([[-1,-2,-1],[0,0,0],[1,2,1]]).unsqueeze(0).unsqueeze(0)
        self.register_buffer('sx', sx)
        self.register_buffer('sy', sy)

    def _edges(self, t):
        B,C,D,H,W = t.shape
        g  = (0.299*t[:,0] + 0.587*t[:,1] + 0.114*t[:,2]).reshape(B*D,1,H,W)
        gx = F.conv2d(g, self.sx, padding=1)
        gy = F.conv2d(g, self.sy, padding=1)
        return torch.sqrt(gx**2 + gy**2 + 1e-6)

    def forward(self, enhanced, original):
        return torch.mean(torch.abs(self._edges(enhanced) - self._edges(original))) + 1e-6


class MSSSIMLoss(nn.Module):
    """Eq. 13"""
    def forward(self, enhanced, original):
        B,C,D,H,W = enhanced.shape
        total = 0.0
        for d in range(D):
            total += 1.0 - ms_ssim(enhanced[:,:,d], original[:,:,d], data_range=1.0, size_average=True)
        return total / D


class Zero3DCELoss(nn.Module):
    """Eq. 14: weighted sum of all 6 losses."""
    def __init__(self, w1=10, w2=200, w3=1, w4=5, w5=5, w6=1, E=0.4):
        super().__init__()
        self.w1,self.w2,self.w3 = w1,w2,w3
        self.w4,self.w5,self.w6 = w4,w5,w6
        self.exp     = ExposureControlLoss(E=E)
        self.smooth  = IlluminationSmoothnessLoss()
        self.spatial = SpatialConsistencyLoss()
        self.edge    = EdgeDetectionLoss()
        self.color   = ColorConstancyLoss()
        self.msssim  = MSSSIMLoss()

    def forward(self, enhanced, original, alpha_maps):
        l = {
            'exp':     self.exp(enhanced),
            'smooth':  self.smooth(alpha_maps),
            'spatial': self.spatial(enhanced, original),
            'edge':    self.edge(enhanced, original),
            'color':   self.color(enhanced),
            'msssim':  self.msssim(enhanced, original),
        }
        total = (self.w1*l['exp'] + self.w2*l['smooth'] + self.w3*l['spatial'] +
                 self.w4*l['edge'] + self.w5*l['color'] + self.w6*l['msssim'])
        return total, {k: v.item() for k,v in l.items()} | {'total': total.item()}


print('Loss functions defined ✓')

"""## Step 5: Dataset Loader"""

import glob
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image


class LowLightDataset(Dataset):
    """
    Loads low-light images and returns D=2 frame clips.
    Zero-reference: only low-light images needed, no paired GT.
    """
    def __init__(self, data_dir, img_size=256, video_mode=False):
        self.video_mode = video_mode
        self.transform  = transforms.Compose([
            transforms.Resize((img_size, img_size)),
            transforms.ToTensor(),
        ])
        exts = ['*.jpg','*.jpeg','*.png','*.bmp']
        self.images = []
        for e in exts:
            self.images += glob.glob(os.path.join(data_dir, '**', e), recursive=True)
        self.images = sorted(self.images)
        assert len(self.images) > 0, f'No images found in {data_dir}'
        print(f'Dataset: {len(self.images)} images found.')

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img1 = self.transform(Image.open(self.images[idx]).convert('RGB'))
        if self.video_mode and idx + 1 < len(self.images):
            img2 = self.transform(Image.open(self.images[idx+1]).convert('RGB'))
        else:
            img2 = img1.clone()
        return torch.stack([img1, img2], dim=1)


dataset = LowLightDataset(DATA_DIR, img_size=256, video_mode=False)
sample  = dataset[0]
print(f'Sample clip shape: {sample.shape}')

"""## Step 6: Training Configuration
**Key changes from previous run:**
- `E_TARGET` lowered from `0.6` to `0.4` — prevents over-brightening already-bright regions (fixes color artifacts)
- Surveillance frames now included in training data — model learns your CCTV lighting conditions

"""

# ── HYPERPARAMETERS ───────────────────────────────────────────────────
EPOCHS      = 100
BATCH_SIZE  = 8
LR          = 1e-4
IMG_SIZE    = 256
VIDEO_MODE  = False
SAVE_EVERY  = 10

# Loss weights (Eq. 14)
W_EXP     = 10.0
W_SMOOTH  = 200.0
W_SPATIAL = 1.0
W_EDGE    = 5.0
W_COLOR   = 5.0
W_MSSSIM  = 1.0
E_TARGET  = 0.3   # lowered from 0.6 — prevents over-brightening bright regions
# ─────────────────────────────────────────────────────────────────────

loader    = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True,
                       num_workers=2, pin_memory=True, drop_last=True)
model     = Zero3DCE().to(device)
criterion = Zero3DCELoss(W_EXP,W_SMOOTH,W_SPATIAL,W_EDGE,W_COLOR,W_MSSSIM,E_TARGET).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=LR, weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)

start_epoch = 0
if RESUME and os.path.exists(RESUME):
    ckpt = torch.load(RESUME, map_location=device)
    model.load_state_dict(ckpt['model'])
    optimizer.load_state_dict(ckpt['optimizer'])
    start_epoch = ckpt['epoch'] + 1
    print(f'Resumed from epoch {start_epoch}')

print('Training config ready ✓')
print(f'Batches per epoch : {len(loader)}')
print(f'Total epochs      : {EPOCHS} (starting from {start_epoch})')
print(f'Exposure target   : {E_TARGET}')

"""## Step 7: Train
> If Colab disconnects: set `RESUME` in Step 1 to the last checkpoint path, then re-run from Step 6.

"""

import math

for epoch in range(start_epoch, EPOCHS):
    model.train()
    totals = {k: 0.0 for k in ['exp','smooth','spatial','edge','color','msssim','total']}
    n = 0

    for i, clip in enumerate(loader):
        original = clip.to(device)
        optimizer.zero_grad()
        enhanced, alpha_maps = model.forward_with_alphas(original)
        loss, loss_dict = criterion(enhanced, original, alpha_maps)

        if not math.isfinite(loss.item()):
            print(f'  [E{epoch+1} B{i}] Non-finite loss — skipped')
            optimizer.zero_grad()
            continue

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()

        for k,v in loss_dict.items(): totals[k] += v
        n += 1

        if i % 50 == 0:
            print(f'  Epoch [{epoch+1}/{EPOCHS}] Batch [{i}/{len(loader)}] '
                  f'total={loss_dict["total"]:.4f} '
                  f'exp={loss_dict["exp"]:.4f} '
                  f'smooth={loss_dict["smooth"]:.4f} '
                  f'edge={loss_dict["edge"]:.4f}')

    scheduler.step()
    avg = {k: v/max(n,1) for k,v in totals.items()}
    print(f'\n=== Epoch {epoch+1}/{EPOCHS} | '
          f'total={avg["total"]:.4f} exp={avg["exp"]:.4f} '
          f'smooth={avg["smooth"]:.4f} color={avg["color"]:.4f} '
          f'edge={avg["edge"]:.4f} msssim={avg["msssim"]:.4f} ===\n')

    if (epoch + 1) % SAVE_EVERY == 0:
        path = os.path.join(SAVE_DIR, f'zero3dce_epoch{epoch+1:03d}.pth')
        torch.save({
            'epoch': epoch, 'model': model.state_dict(),
            'optimizer': optimizer.state_dict(), 'losses': avg
        }, path)
        print(f'Checkpoint saved -> {path}')

final_path = os.path.join(SAVE_DIR, 'zero3dce_final.pth')
torch.save(model.state_dict(), final_path)
print(f'\nTraining complete. Final model -> {final_path}')

!pip install pytorch-msssim -q

# ── Compute PSNR / SSIM: Raw vs Zero-DCE vs Zero-3DCE ──────────────
import torch, glob, os
from torchvision import transforms
from PIL import Image
from pytorch_msssim import ssim

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
tf = transforms.Compose([transforms.Resize((256,256)), transforms.ToTensor()])

def psnr(img1, img2):
    mse = torch.mean((img1 - img2) ** 2)
    if mse == 0:
        return 100.0
    return 10 * torch.log10(1.0 / mse).item()

def compute_metrics(raw_dir, enhanced_dir):
    psnr_vals, ssim_vals = [], []
    raw_imgs = sorted(glob.glob(f'{raw_dir}/*.jpg') + glob.glob(f'{raw_dir}/*.png'))

    for raw_path in raw_imgs:
        fname = os.path.basename(raw_path)
        enh_path = os.path.join(enhanced_dir, fname)
        if not os.path.exists(enh_path):
            continue

        raw_img = tf(Image.open(raw_path).convert('RGB')).unsqueeze(0).to(device)
        enh_img = tf(Image.open(enh_path).convert('RGB')).unsqueeze(0).to(device)

        psnr_vals.append(psnr(raw_img, enh_img))
        ssim_vals.append(ssim(raw_img, enh_img, data_range=1.0).item())

    return sum(psnr_vals)/len(psnr_vals), sum(ssim_vals)/len(ssim_vals), len(psnr_vals)

# Compare Raw vs each enhancement, using test split
raw_dir      = '/content/datasets/Raw_Dataset/test/images'
zerodce_dir  = '/content/datasets/ZeroDCE_Dataset/test/images'
zero3dce_dir = '/content/datasets/Zero3DCE_Dataset/test/images'

zerodce_psnr, zerodce_ssim, n1 = compute_metrics(raw_dir, zerodce_dir)
zero3dce_psnr, zero3dce_ssim, n2 = compute_metrics(raw_dir, zero3dce_dir)

print(f'Zero-DCE  vs Raw  ({n1} images): PSNR = {zerodce_psnr:.2f} dB, SSIM = {zerodce_ssim:.4f}')
print(f'Zero-3DCE vs Raw ({n2} images): PSNR = {zero3dce_psnr:.2f} dB, SSIM = {zero3dce_ssim:.4f}')
print(f'\nDifference: PSNR = {zero3dce_psnr - zerodce_psnr:+.2f} dB, SSIM = {zero3dce_ssim - zerodce_ssim:+.4f}')

import os, glob

for name, d in [
    ('Raw', '/content/datasets/Raw_Dataset/test/images'),
    ('ZeroDCE', '/content/datasets/ZeroDCE_Dataset/test/images'),
    ('Zero3DCE', '/content/datasets/Zero3DCE_Dataset/test/images'),
]:
    if os.path.exists(d):
        imgs = glob.glob(f'{d}/*.jpg') + glob.glob(f'{d}/*.png')
        print(f'{name}: {len(imgs)} images')
        if imgs:
            print(f'  sample: {os.path.basename(imgs[0])}')
    else:
        print(f'{name}: directory not found')